# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "server"
version = "0.1.0"
edition = "2018"

[features]
concurrency = ["tokio/rt-multi-thread", "num_cpus"]
default = ["concurrency"]

[dependencies]
config-compiler = { path = "../config-compiler" }
tokio = { version = "1.12.0", features = ["net", "macros", "io-util", "rt"] }
futures = { version = "0.3.0", features = ["thread-pool"]}
num_cpus = { version = "1", optional = true }
tokio-util = { version="0.6.3", features=["codec", "io"] }
bytes = "1.1.0"
